name: Bundle Stack-chan Firmware
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - name: Bundle
        run: source $HOME/.local/share/xs-dev-export.sh && npm run bundle
        working-directory: ./firmware
      - name: Upload Firmware Bundle
        uses: actions/upload-artifact@v2
        with:
          name: firmware-bundle
          path: ./firmware/stackchan/tech.moddable.stackchan

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pages Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download Firmware Bundle
        uses: actions/download-artifact@v2
        with:
          name: firmware-bundle
          path: ./firmware-bundle
      - name: Move Bundle
        run: |
          mkdir -p ./web/flash/tech.moddable.stackchan
          mv firmware-bundle/* ./web/flash/tech.moddable.stackchan
      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Deploy firmware bundle from ${{ github.sha }}"
          git push
